# Generated by Django 3.2 on 2022-03-16 23:46

import cloudinary.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('apartment_name', models.CharField(choices=[('Tony', 'Tony Apartment for max4 people'), ('Matea', 'Matea apartment for max4 people'), ('Martina', 'Martina apartment for max6 people')], max_length=10, primary_key=True, serialize=False)),
                ('beds_nr', models.IntegerField()),
                ('kitchen', models.BooleanField(default=True)),
                ('balcony', models.BooleanField(default=True)),
                ('seaview', models.BooleanField(default=True)),
                ('AC', models.BooleanField(default=True)),
                ('front_image', cloudinary.models.CloudinaryField(default='first_img', max_length=255, verbose_name='front_image')),
                ('front_image2', cloudinary.models.CloudinaryField(default='second_img', max_length=255, verbose_name='front_image2')),
                ('front_image3', cloudinary.models.CloudinaryField(default='third_img', max_length=255, verbose_name='front_image3')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('guest_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('ph_number', models.CharField(max_length=40, validators=[django.core.validators.RegexValidator('^\\d{3}-\\d{3}-\\d{4}$')])),
                ('email', models.EmailField(max_length=254)),
                ('kids', models.BooleanField(blank=True, default=False)),
                ('pets', models.BooleanField(blank=True, default=False)),
            ],
        ),
    ]
